services:
    postgres:
        image: postgres:18-alpine
        container_name: product_importer_postgres
        restart: always
        environment:
            POSTGRES_DB: product_importer_db
            POSTGRES_USER: product_importer
            POSTGRES_PASSWORD: masterkey
        ports:
            - "5430:5432"
        volumes:
            - product_importer_postgres_data:/var/lib/postgresql/data

volumes:
    product_importer_postgres_data:
