
services:
    teste:
        image: postgres:18-alpine
        container_name: teste_postgres
        restart: always
        environment:
            POSTGRES_DB: teste_db
            POSTGRES_USER: teste
            POSTGRES_PASSWORD: 123456
        ports:
            - "5422:5432"
        volumes:
            - teste_postgres_data:/var/lib/postgresql/data

volumes:
    teste_postgres_data: